apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: a3VCccc433( base64 encoded Azure Storage account name)SDW23SX==
  azurestorageaccountkey: 88uuuhGRFFS( base64 encoded Azure Storage account name)Ca2pwa$alRLUTNOWGt4L1ZGTGxGBVF$66sfcwewgRRdcsdLb0xrcmx6==
